# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import textSender_pb2 as textSender__pb2


class calculatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SquareRoot = channel.unary_unary(
                '/calculator/SquareRoot',
                request_serializer=textSender__pb2.Number.SerializeToString,
                response_deserializer=textSender__pb2.Number.FromString,
                )


class calculatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SquareRoot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_calculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SquareRoot': grpc.unary_unary_rpc_method_handler(
                    servicer.SquareRoot,
                    request_deserializer=textSender__pb2.Number.FromString,
                    response_serializer=textSender__pb2.Number.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class calculator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SquareRoot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator/SquareRoot',
            textSender__pb2.Number.SerializeToString,
            textSender__pb2.Number.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class wordInverterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Invert = channel.unary_unary(
                '/wordInverter/Invert',
                request_serializer=textSender__pb2.Word.SerializeToString,
                response_deserializer=textSender__pb2.Word.FromString,
                )


class wordInverterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Invert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_wordInverterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Invert': grpc.unary_unary_rpc_method_handler(
                    servicer.Invert,
                    request_deserializer=textSender__pb2.Word.FromString,
                    response_serializer=textSender__pb2.Word.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wordInverter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class wordInverter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Invert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wordInverter/Invert',
            textSender__pb2.Word.SerializeToString,
            textSender__pb2.Word.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
