# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: textSender.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10textSender.proto\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x02\"\x15\n\x04Word\x12\r\n\x05value\x18\x01 \x01(\t2.\n\ncalculator\x12 \n\nSquareRoot\x12\x07.Number\x1a\x07.Number\"\x00\x32(\n\x0cwordInverter\x12\x18\n\x06Invert\x12\x05.Word\x1a\x05.Word\"\x00\x62\x06proto3')



_NUMBER = DESCRIPTOR.message_types_by_name['Number']
_WORD = DESCRIPTOR.message_types_by_name['Word']
Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), {
  'DESCRIPTOR' : _NUMBER,
  '__module__' : 'textSender_pb2'
  # @@protoc_insertion_point(class_scope:Number)
  })
_sym_db.RegisterMessage(Number)

Word = _reflection.GeneratedProtocolMessageType('Word', (_message.Message,), {
  'DESCRIPTOR' : _WORD,
  '__module__' : 'textSender_pb2'
  # @@protoc_insertion_point(class_scope:Word)
  })
_sym_db.RegisterMessage(Word)

_CALCULATOR = DESCRIPTOR.services_by_name['calculator']
_WORDINVERTER = DESCRIPTOR.services_by_name['wordInverter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NUMBER._serialized_start=20
  _NUMBER._serialized_end=43
  _WORD._serialized_start=45
  _WORD._serialized_end=66
  _CALCULATOR._serialized_start=68
  _CALCULATOR._serialized_end=114
  _WORDINVERTER._serialized_start=116
  _WORDINVERTER._serialized_end=156
# @@protoc_insertion_point(module_scope)
